slice_name: Course Completion
description: How many users have completed what % of a course?
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 645__table
  viz_type: echarts_timeseries_bar
  slice_id: 1261
  x_axis: completion_bucket
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: completion_bucket
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 7762
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: STRING
      type_generic: 1
      verbose_name: Completion Bucket
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(Completion Bucket)
    optionName: metric_5p89rntvdpq_j0c7lzlcb9
    sqlExpression: null
  groupby:
  - course_name
  adhoc_filters:
  - clause: WHERE
    comparator: '%type@course+block@course'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_occ2oc7akeh_kv2rbeu4std
    isExtra: false
    isNew: false
    operator: LIKE
    operatorId: LIKE
    sqlExpression: null
    subject: entity_id
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_titbyzbrfq9_9j3vgskqe6l
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: emission_time
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelRotation: 0
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateXAxis: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 241
query_context: '{"datasource":{"id":645,"type":"table"},"force":false,"queries":[{"filters":[{"col":"entity_id","op":"LIKE","val":"%type@course+block@course"},{"col":"emission_time","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"completion_bucket","label":"completion_bucket","expressionType":"SQL"},"course_name"],"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"completion_bucket","description":null,"expression":null,"filterable":true,"groupby":true,"id":7762,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":"Completion
  Bucket","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(Completion
  Bucket)","optionName":"metric_5p89rntvdpq_j0c7lzlcb9","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"completion_bucket","description":null,"expression":null,"filterable":true,"groupby":true,"id":7762,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":"Completion
  Bucket","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(Completion
  Bucket)","optionName":"metric_5p89rntvdpq_j0c7lzlcb9","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["course_name"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["completion_bucket"],"columns":["course_name"],"aggregates":{"COUNT(Completion
  Bucket)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"COUNT(Completion
  Bucket)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"645__table","viz_type":"echarts_timeseries_bar","slice_id":1261,"x_axis":"completion_bucket","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"completion_bucket","description":null,"expression":null,"filterable":true,"groupby":true,"id":7762,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":"Completion
  Bucket","warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(Completion
  Bucket)","optionName":"metric_5p89rntvdpq_j0c7lzlcb9","sqlExpression":null}],"groupby":["course_name"],"adhoc_filters":[{"clause":"WHERE","comparator":"%type@course+block@course","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_occ2oc7akeh_kv2rbeu4std","isExtra":false,"isNew":false,"operator":"LIKE","operatorId":"LIKE","sqlExpression":null,"subject":"entity_id"},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_titbyzbrfq9_9j3vgskqe6l","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":null,"subject":"emission_time"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title":"","x_axis_title_margin":15,"y_axis_title":"","y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelRotation":0,"y_axis_format":"SMART_NUMBER","logAxis":false,"minorSplitLine":false,"truncateXAxis":true,"truncateYAxis":false,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[241],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a7846e20-3ad7-4705-b441-8bda24f4ab81
version: 1.0.0
dataset_uuid: 32d887ee-d2cd-4220-a5f6-aff37e4e8083
